### ISSUE TITLE
`make` commad fails on `id2title`

### ISSUE THREAD

**Issue by JoWohlen** [octaviaguo/Constrained-Labeled-Data-Generation#1]
Hey I encounter the following problem when running your `make-command`.

when i am running the make command: 
```sh
make DATE=20220220 LANG=de DUMPDIR_BASE=./dump OUTDIR_BASE=./out PYTONBIN=python all
```
the whole dump is downloaded perfectly well.
When the text is extracted i get some warnings with some articles (around 50). But as they are warnings I assume that is not a big problem.
![image](https://user-images.githubusercontent.com/44275743/174334285-2f9143c9-77f4-49a9-9cfa-8d786ce2f4e6.png)
Unfortunately when `making id2tile` the whole script fails for me, see error below:
![image](https://user-images.githubusercontent.com/44275743/174334584-ecf80e23-e716-4a22-8f11-151d8df08981.png)
strangely the not found file `dewiki-20220220-page.sql.gz` does actually exist at the specified folder
![image](https://user-images.githubusercontent.com/44275743/174336325-20260e1a-c83e-4628-9ab4-48a566b315cb.png)
Do you have any idea why the script fails? Is there any other way I could try?
What makes me wonder is that the `.spl.gz` files are very small, that is not normal is it?

---

I already tried deleting the `/out` folder and to rerun the `make-command`.

**Comment by octaviaguo** [comment]
Hi @JoWohlen! Thanks for your feedback!
I re-ran the `make-command` and didn't get the error. Can you check the argument `PATH_OUTDIR` in `extract_wikidump.sh`? You may need the full path of the output folder.

**Comment by JoWohlen** [comment]
Hey thanks for your response. I realized this error was caused by the code of [Wikidump](https://github.com/CogComp/wikidump-preprocessing)

Solution was to:
1. go into [wikidump-preprocessing](https://github.com/CogComp/wikidump-preprocessing)/[dp](https://github.com/CogComp/wikidump-preprocessing/tree/master/dp)/count_popular_entities_v2.py
2. find function `process_wikicontent(self, page_content, page_id, page_title)`
3. add 
   ```py
            except TypeError:
            logging.info("bs4 failed %d times", self.bs4_failures)
            return
   ```
under the try-except block

this prevented an error that would not download the dump properly --> resulted in the make command not working

**Comment by JoWohlen** [comment]
This is an Issue with Wikidump thats why I closed it :)
